// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqiqvapqgdjzvngekydm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxaXF2YXBxZ2RqenZuZ2VreWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzUwNjQsImV4cCI6MjA3MTYxMTA2NH0.GPRtbSpIo2lx4NrDC-oC2M6Wff5UEm3PFwjGjZhiFMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});